# Generated by Django 4.1.3 on 2022-12-05 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="samples",
            name="fabrication",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="samples",
            name="fig_xrd",
            field=models.ImageField(default="XRD_data/", upload_to="XRD_data/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="samples",
            name="fig_xrr",
            field=models.ImageField(default="XRR_data/", upload_to="XRR_data/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="baseuuid",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("809dcb0d-5c0f-4679-a8e1-57071d435db9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
