# Generated by Django 4.1.3 on 2022-12-05 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_second_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="samples",
            name="formula",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="baseuuid",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f3b0b54-b053-44e8-bca6-a0ba8c23a009"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="samples",
            name="fig_xrd",
            field=models.ImageField(default="XRD_data/", upload_to="XRD_data/"),
        ),
        migrations.AlterField(
            model_name="samples",
            name="fig_xrr",
            field=models.ImageField(default="XRR_data/", upload_to="XRR_data/"),
        ),
    ]
