# Generated by Django 4.1.3 on 2022-12-05 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_new_size_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuuid",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6411c750-17c8-4dae-8503-2c75f84b68fd"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="samples",
            name="formula",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
